# Cardiac-Arrest-Prediction

In [1]:
import numpy as np #used for numerical analysis
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC # "Support vector classifier"
from sklearn.metrics import accuracy_score,confusion_matrix

import sklearn.metrics as metrics

In [2]:
#https://www.kaggle.com/andrewmvd/heart-failure-clinical-data
dataset = pd.read_csv("C:\\Users\\Aayushii\\Desktop\\smart_bridge\\Cardiac_Arrest_Prediction\\heart_failure_dataset.csv")

In [13]:
dataset.isnull().any() # checking for any null values
dataset.isnull().sum() # counting all null values

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [16]:
dataset.drop("time",axis = 1, inplace = True)
dataset["death_event"] = dataset["DEATH_EVENT"]
dataset.drop("DEATH_EVENT",axis = 1, inplace = True)

In [17]:
x = dataset.iloc[:, 0:11].values
y = dataset.iloc[:, 11:12].values

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [19]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [20]:
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train) 

E:\Anaconda\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(kernel='linear', random_state=0)

In [21]:
import pickle
pickle.dump(classifier, open('C:\\Users\\Aayushii\\Desktop\\smart_bridge\\Cardiac_Arrest_Prediction\\cardiac_arrest_model.pkl','wb'))

In [22]:
classifier_pred = classifier.predict(x_test)
classifier_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [23]:
classifier_acc = accuracy_score(y_test, classifier_pred)
classifier_acc

0.7

In [24]:
classifier_cm = confusion_matrix(y_test, classifier_pred)
classifier_cm

array([[34,  3],
       [15,  8]], dtype=int64)

In [25]:
classifier_p = classifier.predict(sc.transform([[69, 1, 59, 1, 60, 0, 170000, 1, 130, 0, 0]]))
classifier_p

array([0], dtype=int64)